// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/ClientRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DnD.Service {

  /// <summary>Holder for reflection information generated from proto/ClientRequest.proto</summary>
  public static partial class ClientRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/ClientRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chlwcm90by9DbGllbnRSZXF1ZXN0LnByb3RvEgtEbkQuc2VydmljZSJZCg1D",
            "bGllbnRSZXF1ZXN0EjMKC3JlcXVlc3RUeXBlGAEgASgOMh4uRG5ELnNlcnZp",
            "Y2UuQ2xpZW50UmVxdWVzdFR5cGUSEwoLcmVxdWVzdERhdGEYAiABKAwqRwoR",
            "Q2xpZW50UmVxdWVzdFR5cGUSFQoRQ0xJRU5UX0NPTk5FQ1RJT04QABIbChdU",
            "SUxFX0dFTkVSQVRJT05fUkVRVUVTVBABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DnD.Service.ClientRequestType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DnD.Service.ClientRequest), global::DnD.Service.ClientRequest.Parser, new[]{ "RequestType", "RequestData" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ClientRequestType {
    [pbr::OriginalName("CLIENT_CONNECTION")] ClientConnection = 0,
    [pbr::OriginalName("TILE_GENERATION_REQUEST")] TileGenerationRequest = 1,
  }

  #endregion

  #region Messages
  public sealed partial class ClientRequest : pb::IMessage<ClientRequest> {
    private static readonly pb::MessageParser<ClientRequest> _parser = new pb::MessageParser<ClientRequest>(() => new ClientRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DnD.Service.ClientRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientRequest(ClientRequest other) : this() {
      requestType_ = other.requestType_;
      requestData_ = other.requestData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientRequest Clone() {
      return new ClientRequest(this);
    }

    /// <summary>Field number for the "requestType" field.</summary>
    public const int RequestTypeFieldNumber = 1;
    private global::DnD.Service.ClientRequestType requestType_ = global::DnD.Service.ClientRequestType.ClientConnection;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DnD.Service.ClientRequestType RequestType {
      get { return requestType_; }
      set {
        requestType_ = value;
      }
    }

    /// <summary>Field number for the "requestData" field.</summary>
    public const int RequestDataFieldNumber = 2;
    private pb::ByteString requestData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString RequestData {
      get { return requestData_; }
      set {
        requestData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestType != other.RequestType) return false;
      if (RequestData != other.RequestData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestType != global::DnD.Service.ClientRequestType.ClientConnection) hash ^= RequestType.GetHashCode();
      if (RequestData.Length != 0) hash ^= RequestData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RequestType != global::DnD.Service.ClientRequestType.ClientConnection) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RequestType);
      }
      if (RequestData.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(RequestData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestType != global::DnD.Service.ClientRequestType.ClientConnection) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestType);
      }
      if (RequestData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RequestData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientRequest other) {
      if (other == null) {
        return;
      }
      if (other.RequestType != global::DnD.Service.ClientRequestType.ClientConnection) {
        RequestType = other.RequestType;
      }
      if (other.RequestData.Length != 0) {
        RequestData = other.RequestData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestType = (global::DnD.Service.ClientRequestType) input.ReadEnum();
            break;
          }
          case 18: {
            RequestData = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
