// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/RequestType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/RequestType.proto</summary>
public static partial class RequestTypeReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/RequestType.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static RequestTypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chdwcm90by9SZXF1ZXN0VHlwZS5wcm90byo5CgtSZXF1ZXN0VHlwZRIVChFD",
          "TElFTlRfQ09OTkVDVElPThAAEhMKD1RJTEVfR0VORVJBVElPThABYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RequestType), }, null));
  }
  #endregion

}
#region Enums
public enum RequestType {
  [pbr::OriginalName("CLIENT_CONNECTION")] ClientConnection = 0,
  [pbr::OriginalName("TILE_GENERATION")] TileGeneration = 1,
}

#endregion


#endregion Designer generated code
