// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TerrainList.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DnD.Terrain {

  /// <summary>Holder for reflection information generated from TerrainList.proto</summary>
  public static partial class TerrainListReflection {

    #region Descriptor
    /// <summary>File descriptor for TerrainList.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TerrainListReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFUZXJyYWluTGlzdC5wcm90bxILRG5ELlRlcnJhaW4aDVRlcnJhaW4ucHJv",
            "dG8iNQoLVGVycmFpbkxpc3QSJgoIdGVycmFpbnMYASADKAsyFC5EbmQuVGVy",
            "cmFpbi5UZXJyYWluQiQKC0RuRC5UZXJyYWluQhVUZXJyYWluTGlzdE91dGVy",
            "Q2xhc3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dnd.Terrain.TerrainReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DnD.Terrain.TerrainList), global::DnD.Terrain.TerrainList.Parser, new[]{ "Terrains" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TerrainList : pb::IMessage<TerrainList> {
    private static readonly pb::MessageParser<TerrainList> _parser = new pb::MessageParser<TerrainList>(() => new TerrainList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TerrainList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DnD.Terrain.TerrainListReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TerrainList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TerrainList(TerrainList other) : this() {
      terrains_ = other.terrains_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TerrainList Clone() {
      return new TerrainList(this);
    }

    /// <summary>Field number for the "terrains" field.</summary>
    public const int TerrainsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Dnd.Terrain.Terrain> _repeated_terrains_codec
        = pb::FieldCodec.ForMessage(10, global::Dnd.Terrain.Terrain.Parser);
    private readonly pbc::RepeatedField<global::Dnd.Terrain.Terrain> terrains_ = new pbc::RepeatedField<global::Dnd.Terrain.Terrain>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dnd.Terrain.Terrain> Terrains {
      get { return terrains_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TerrainList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TerrainList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!terrains_.Equals(other.terrains_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= terrains_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      terrains_.WriteTo(output, _repeated_terrains_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += terrains_.CalculateSize(_repeated_terrains_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TerrainList other) {
      if (other == null) {
        return;
      }
      terrains_.Add(other.terrains_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            terrains_.AddEntriesFrom(input, _repeated_terrains_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
