// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TileType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dnd.Terrain {

  /// <summary>Holder for reflection information generated from TileType.proto</summary>
  public static partial class TileTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for TileType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TileTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5UaWxlVHlwZS5wcm90bxILRG5kLlRlcnJhaW4qeAoIVGlsZVR5cGUSEgoO",
            "U1RBTkRBUkRfR1JBU1MQABIVChFMSUdIVF9QQVRDSF9HUkFTUxABEhQKEERB",
            "UktfUEFUQ0hfR1JBU1MQAhIRCg1TVEFOREFSRF9UUkVFEAMSCAoEUk9DSxAE",
            "Eg4KCkdJQU5UX1JPQ0sQBUIhCgtEbkQuVGVycmFpbkISVGlsZVR5cGVPdXRl",
            "ckNsYXNzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Dnd.Terrain.TileType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TileType {
    [pbr::OriginalName("STANDARD_GRASS")] StandardGrass = 0,
    [pbr::OriginalName("LIGHT_PATCH_GRASS")] LightPatchGrass = 1,
    [pbr::OriginalName("DARK_PATCH_GRASS")] DarkPatchGrass = 2,
    [pbr::OriginalName("STANDARD_TREE")] StandardTree = 3,
    [pbr::OriginalName("ROCK")] Rock = 4,
    [pbr::OriginalName("GIANT_ROCK")] GiantRock = 5,
  }

  #endregion

}

#endregion Designer generated code
