// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ClientRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DnD.Service {

  /// <summary>Holder for reflection information generated from ClientRequest.proto</summary>
  public static partial class ClientRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for ClientRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNDbGllbnRSZXF1ZXN0LnByb3RvEgtEbkQuc2VydmljZRoMQ2xpZW50LnBy",
            "b3RvIq0BCg1DbGllbnRSZXF1ZXN0EiMKBmNsaWVudBgBIAEoCzITLkRuRC5z",
            "ZXJ2aWNlLkNsaWVudBIvCgdyZXFUeXBlGAIgASgOMh4uRG5ELnNlcnZpY2Uu",
            "Q2xpZW50UmVxdWVzdFR5cGUSEwoLcmVxdWVzdERhdGEYAyABKAwSMQoNY2xp",
            "ZW50Q29udGV4dBgEIAEoCzIaLkRuRC5zZXJ2aWNlLkNsaWVudENvbnRleHQi",
            "pgEKDUNsaWVudENvbnRleHQSOQoQcGxheWVyVXBkYXRlVHlwZRgBIAEoCzId",
            "LkRuRC5zZXJ2aWNlLlBsYXllclVwZGF0ZVR5cGVIABI3Cg93b3JsZFVwZGF0",
            "ZVR5cGUYAiABKAsyHC5EbkQuc2VydmljZS5Xb2xyZFVwZGF0ZVR5cGVIABIS",
            "CgpjbGllbnREYXRhGAMgAygMQg0KC0NvbnRleHRUeXBlIpwBChBQbGF5ZXJV",
            "cGRhdGVUeXBlEjkKEHBsYXllclN0YXR1c1R5cGUYASABKA4yHS5EbkQuc2Vy",
            "dmljZS5QbGF5ZXJTdGF0dXNUeXBlSAASPwoTcGxheWVyVHJhbnNmb3JtVHlw",
            "ZRgCIAEoDjIgLkRuRC5zZXJ2aWNlLlBsYXllclRyYW5zZm9ybVR5cGVIAEIM",
            "Cgp1cGRhdGVUeXBlIlgKD1dvbHJkVXBkYXRlVHlwZRI3Cg9wcm9wc1VwZGF0",
            "ZVR5cGUYASABKA4yHC5EbkQuc2VydmljZS5Qcm9wc1VwZGF0ZVR5cGVIAEIM",
            "Cgp1cGRhdGVUeXBlKo8BChFDbGllbnRSZXF1ZXN0VHlwZRIVChFDTElFTlRf",
            "Q09OTkVDVElPThAAEhgKFENMSUVOVF9ESVNDT05ORUNUSU9OEAESEwoPVElM",
            "RV9HRU5FUkFUSU9OEAISDwoLVElMRVNfRkVUQ0gQAxIRCg1DTElFTlRfVVBE",
            "QVRFEAQSEAoMTlBDX0lOU1RBTkNFEAUqJwoQUGxheWVyU3RhdHVzVHlwZRII",
            "CgRKT0lOEAASCQoFTEVBVkUQASo9ChNQbGF5ZXJUcmFuc2Zvcm1UeXBlEhIK",
            "DlVQREFURV9BTE9OR19YEAASEgoOVVBEQVRFX0FMT05HX1kQASozCg9Qcm9w",
            "c1VwZGF0ZVR5cGUSDwoLREVMRVRFX1BST1AQABIPCgtJTlNFUlRfUFJPUBAB",
            "QiYKC0RuRC5zZXJ2aWNlQhdDbGllbnRSZXF1ZXN0T3V0ZXJDbGFzc2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DnD.Service.ClientReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DnD.Service.ClientRequestType), typeof(global::DnD.Service.PlayerStatusType), typeof(global::DnD.Service.PlayerTransformType), typeof(global::DnD.Service.PropsUpdateType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DnD.Service.ClientRequest), global::DnD.Service.ClientRequest.Parser, new[]{ "Client", "ReqType", "RequestData", "ClientContext" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DnD.Service.ClientContext), global::DnD.Service.ClientContext.Parser, new[]{ "PlayerUpdateType", "WorldUpdateType", "ClientData" }, new[]{ "ContextType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DnD.Service.PlayerUpdateType), global::DnD.Service.PlayerUpdateType.Parser, new[]{ "PlayerStatusType", "PlayerTransformType" }, new[]{ "UpdateType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DnD.Service.WolrdUpdateType), global::DnD.Service.WolrdUpdateType.Parser, new[]{ "PropsUpdateType" }, new[]{ "UpdateType" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ClientRequestType {
    [pbr::OriginalName("CLIENT_CONNECTION")] ClientConnection = 0,
    [pbr::OriginalName("CLIENT_DISCONNECTION")] ClientDisconnection = 1,
    /// <summary>
    /// deprecated
    /// </summary>
    [pbr::OriginalName("TILE_GENERATION")] TileGeneration = 2,
    [pbr::OriginalName("TILES_FETCH")] TilesFetch = 3,
    [pbr::OriginalName("CLIENT_UPDATE")] ClientUpdate = 4,
    [pbr::OriginalName("NPC_INSTANCE")] NpcInstance = 5,
  }

  public enum PlayerStatusType {
    [pbr::OriginalName("JOIN")] Join = 0,
    [pbr::OriginalName("LEAVE")] Leave = 1,
  }

  public enum PlayerTransformType {
    [pbr::OriginalName("UPDATE_ALONG_X")] UpdateAlongX = 0,
    [pbr::OriginalName("UPDATE_ALONG_Y")] UpdateAlongY = 1,
  }

  public enum PropsUpdateType {
    [pbr::OriginalName("DELETE_PROP")] DeleteProp = 0,
    [pbr::OriginalName("INSERT_PROP")] InsertProp = 1,
  }

  #endregion

  #region Messages
  public sealed partial class ClientRequest : pb::IMessage<ClientRequest> {
    private static readonly pb::MessageParser<ClientRequest> _parser = new pb::MessageParser<ClientRequest>(() => new ClientRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DnD.Service.ClientRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientRequest(ClientRequest other) : this() {
      client_ = other.client_ != null ? other.client_.Clone() : null;
      reqType_ = other.reqType_;
      requestData_ = other.requestData_;
      clientContext_ = other.clientContext_ != null ? other.clientContext_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientRequest Clone() {
      return new ClientRequest(this);
    }

    /// <summary>Field number for the "client" field.</summary>
    public const int ClientFieldNumber = 1;
    private global::DnD.Service.Client client_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DnD.Service.Client Client {
      get { return client_; }
      set {
        client_ = value;
      }
    }

    /// <summary>Field number for the "reqType" field.</summary>
    public const int ReqTypeFieldNumber = 2;
    private global::DnD.Service.ClientRequestType reqType_ = global::DnD.Service.ClientRequestType.ClientConnection;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DnD.Service.ClientRequestType ReqType {
      get { return reqType_; }
      set {
        reqType_ = value;
      }
    }

    /// <summary>Field number for the "requestData" field.</summary>
    public const int RequestDataFieldNumber = 3;
    private pb::ByteString requestData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString RequestData {
      get { return requestData_; }
      set {
        requestData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "clientContext" field.</summary>
    public const int ClientContextFieldNumber = 4;
    private global::DnD.Service.ClientContext clientContext_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DnD.Service.ClientContext ClientContext {
      get { return clientContext_; }
      set {
        clientContext_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Client, other.Client)) return false;
      if (ReqType != other.ReqType) return false;
      if (RequestData != other.RequestData) return false;
      if (!object.Equals(ClientContext, other.ClientContext)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (client_ != null) hash ^= Client.GetHashCode();
      if (ReqType != global::DnD.Service.ClientRequestType.ClientConnection) hash ^= ReqType.GetHashCode();
      if (RequestData.Length != 0) hash ^= RequestData.GetHashCode();
      if (clientContext_ != null) hash ^= ClientContext.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (client_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Client);
      }
      if (ReqType != global::DnD.Service.ClientRequestType.ClientConnection) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ReqType);
      }
      if (RequestData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(RequestData);
      }
      if (clientContext_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ClientContext);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (client_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Client);
      }
      if (ReqType != global::DnD.Service.ClientRequestType.ClientConnection) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReqType);
      }
      if (RequestData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RequestData);
      }
      if (clientContext_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClientContext);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientRequest other) {
      if (other == null) {
        return;
      }
      if (other.client_ != null) {
        if (client_ == null) {
          Client = new global::DnD.Service.Client();
        }
        Client.MergeFrom(other.Client);
      }
      if (other.ReqType != global::DnD.Service.ClientRequestType.ClientConnection) {
        ReqType = other.ReqType;
      }
      if (other.RequestData.Length != 0) {
        RequestData = other.RequestData;
      }
      if (other.clientContext_ != null) {
        if (clientContext_ == null) {
          ClientContext = new global::DnD.Service.ClientContext();
        }
        ClientContext.MergeFrom(other.ClientContext);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (client_ == null) {
              Client = new global::DnD.Service.Client();
            }
            input.ReadMessage(Client);
            break;
          }
          case 16: {
            ReqType = (global::DnD.Service.ClientRequestType) input.ReadEnum();
            break;
          }
          case 26: {
            RequestData = input.ReadBytes();
            break;
          }
          case 34: {
            if (clientContext_ == null) {
              ClientContext = new global::DnD.Service.ClientContext();
            }
            input.ReadMessage(ClientContext);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ClientContext : pb::IMessage<ClientContext> {
    private static readonly pb::MessageParser<ClientContext> _parser = new pb::MessageParser<ClientContext>(() => new ClientContext());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientContext> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DnD.Service.ClientRequestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientContext() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientContext(ClientContext other) : this() {
      clientData_ = other.clientData_.Clone();
      switch (other.ContextTypeCase) {
        case ContextTypeOneofCase.PlayerUpdateType:
          PlayerUpdateType = other.PlayerUpdateType.Clone();
          break;
        case ContextTypeOneofCase.WorldUpdateType:
          WorldUpdateType = other.WorldUpdateType.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientContext Clone() {
      return new ClientContext(this);
    }

    /// <summary>Field number for the "playerUpdateType" field.</summary>
    public const int PlayerUpdateTypeFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DnD.Service.PlayerUpdateType PlayerUpdateType {
      get { return contextTypeCase_ == ContextTypeOneofCase.PlayerUpdateType ? (global::DnD.Service.PlayerUpdateType) contextType_ : null; }
      set {
        contextType_ = value;
        contextTypeCase_ = value == null ? ContextTypeOneofCase.None : ContextTypeOneofCase.PlayerUpdateType;
      }
    }

    /// <summary>Field number for the "worldUpdateType" field.</summary>
    public const int WorldUpdateTypeFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DnD.Service.WolrdUpdateType WorldUpdateType {
      get { return contextTypeCase_ == ContextTypeOneofCase.WorldUpdateType ? (global::DnD.Service.WolrdUpdateType) contextType_ : null; }
      set {
        contextType_ = value;
        contextTypeCase_ = value == null ? ContextTypeOneofCase.None : ContextTypeOneofCase.WorldUpdateType;
      }
    }

    /// <summary>Field number for the "clientData" field.</summary>
    public const int ClientDataFieldNumber = 3;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_clientData_codec
        = pb::FieldCodec.ForBytes(26);
    private readonly pbc::RepeatedField<pb::ByteString> clientData_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<pb::ByteString> ClientData {
      get { return clientData_; }
    }

    private object contextType_;
    /// <summary>Enum of possible cases for the "ContextType" oneof.</summary>
    public enum ContextTypeOneofCase {
      None = 0,
      PlayerUpdateType = 1,
      WorldUpdateType = 2,
    }
    private ContextTypeOneofCase contextTypeCase_ = ContextTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContextTypeOneofCase ContextTypeCase {
      get { return contextTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearContextType() {
      contextTypeCase_ = ContextTypeOneofCase.None;
      contextType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientContext);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientContext other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PlayerUpdateType, other.PlayerUpdateType)) return false;
      if (!object.Equals(WorldUpdateType, other.WorldUpdateType)) return false;
      if(!clientData_.Equals(other.clientData_)) return false;
      if (ContextTypeCase != other.ContextTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (contextTypeCase_ == ContextTypeOneofCase.PlayerUpdateType) hash ^= PlayerUpdateType.GetHashCode();
      if (contextTypeCase_ == ContextTypeOneofCase.WorldUpdateType) hash ^= WorldUpdateType.GetHashCode();
      hash ^= clientData_.GetHashCode();
      hash ^= (int) contextTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (contextTypeCase_ == ContextTypeOneofCase.PlayerUpdateType) {
        output.WriteRawTag(10);
        output.WriteMessage(PlayerUpdateType);
      }
      if (contextTypeCase_ == ContextTypeOneofCase.WorldUpdateType) {
        output.WriteRawTag(18);
        output.WriteMessage(WorldUpdateType);
      }
      clientData_.WriteTo(output, _repeated_clientData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (contextTypeCase_ == ContextTypeOneofCase.PlayerUpdateType) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerUpdateType);
      }
      if (contextTypeCase_ == ContextTypeOneofCase.WorldUpdateType) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WorldUpdateType);
      }
      size += clientData_.CalculateSize(_repeated_clientData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientContext other) {
      if (other == null) {
        return;
      }
      clientData_.Add(other.clientData_);
      switch (other.ContextTypeCase) {
        case ContextTypeOneofCase.PlayerUpdateType:
          if (PlayerUpdateType == null) {
            PlayerUpdateType = new global::DnD.Service.PlayerUpdateType();
          }
          PlayerUpdateType.MergeFrom(other.PlayerUpdateType);
          break;
        case ContextTypeOneofCase.WorldUpdateType:
          if (WorldUpdateType == null) {
            WorldUpdateType = new global::DnD.Service.WolrdUpdateType();
          }
          WorldUpdateType.MergeFrom(other.WorldUpdateType);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::DnD.Service.PlayerUpdateType subBuilder = new global::DnD.Service.PlayerUpdateType();
            if (contextTypeCase_ == ContextTypeOneofCase.PlayerUpdateType) {
              subBuilder.MergeFrom(PlayerUpdateType);
            }
            input.ReadMessage(subBuilder);
            PlayerUpdateType = subBuilder;
            break;
          }
          case 18: {
            global::DnD.Service.WolrdUpdateType subBuilder = new global::DnD.Service.WolrdUpdateType();
            if (contextTypeCase_ == ContextTypeOneofCase.WorldUpdateType) {
              subBuilder.MergeFrom(WorldUpdateType);
            }
            input.ReadMessage(subBuilder);
            WorldUpdateType = subBuilder;
            break;
          }
          case 26: {
            clientData_.AddEntriesFrom(input, _repeated_clientData_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PlayerUpdateType : pb::IMessage<PlayerUpdateType> {
    private static readonly pb::MessageParser<PlayerUpdateType> _parser = new pb::MessageParser<PlayerUpdateType>(() => new PlayerUpdateType());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerUpdateType> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DnD.Service.ClientRequestReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerUpdateType() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerUpdateType(PlayerUpdateType other) : this() {
      switch (other.UpdateTypeCase) {
        case UpdateTypeOneofCase.PlayerStatusType:
          PlayerStatusType = other.PlayerStatusType;
          break;
        case UpdateTypeOneofCase.PlayerTransformType:
          PlayerTransformType = other.PlayerTransformType;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerUpdateType Clone() {
      return new PlayerUpdateType(this);
    }

    /// <summary>Field number for the "playerStatusType" field.</summary>
    public const int PlayerStatusTypeFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DnD.Service.PlayerStatusType PlayerStatusType {
      get { return updateTypeCase_ == UpdateTypeOneofCase.PlayerStatusType ? (global::DnD.Service.PlayerStatusType) updateType_ : global::DnD.Service.PlayerStatusType.Join; }
      set {
        updateType_ = value;
        updateTypeCase_ = UpdateTypeOneofCase.PlayerStatusType;
      }
    }

    /// <summary>Field number for the "playerTransformType" field.</summary>
    public const int PlayerTransformTypeFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DnD.Service.PlayerTransformType PlayerTransformType {
      get { return updateTypeCase_ == UpdateTypeOneofCase.PlayerTransformType ? (global::DnD.Service.PlayerTransformType) updateType_ : global::DnD.Service.PlayerTransformType.UpdateAlongX; }
      set {
        updateType_ = value;
        updateTypeCase_ = UpdateTypeOneofCase.PlayerTransformType;
      }
    }

    private object updateType_;
    /// <summary>Enum of possible cases for the "updateType" oneof.</summary>
    public enum UpdateTypeOneofCase {
      None = 0,
      PlayerStatusType = 1,
      PlayerTransformType = 2,
    }
    private UpdateTypeOneofCase updateTypeCase_ = UpdateTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateTypeOneofCase UpdateTypeCase {
      get { return updateTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUpdateType() {
      updateTypeCase_ = UpdateTypeOneofCase.None;
      updateType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerUpdateType);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerUpdateType other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerStatusType != other.PlayerStatusType) return false;
      if (PlayerTransformType != other.PlayerTransformType) return false;
      if (UpdateTypeCase != other.UpdateTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (updateTypeCase_ == UpdateTypeOneofCase.PlayerStatusType) hash ^= PlayerStatusType.GetHashCode();
      if (updateTypeCase_ == UpdateTypeOneofCase.PlayerTransformType) hash ^= PlayerTransformType.GetHashCode();
      hash ^= (int) updateTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (updateTypeCase_ == UpdateTypeOneofCase.PlayerStatusType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PlayerStatusType);
      }
      if (updateTypeCase_ == UpdateTypeOneofCase.PlayerTransformType) {
        output.WriteRawTag(16);
        output.WriteEnum((int) PlayerTransformType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (updateTypeCase_ == UpdateTypeOneofCase.PlayerStatusType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PlayerStatusType);
      }
      if (updateTypeCase_ == UpdateTypeOneofCase.PlayerTransformType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PlayerTransformType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerUpdateType other) {
      if (other == null) {
        return;
      }
      switch (other.UpdateTypeCase) {
        case UpdateTypeOneofCase.PlayerStatusType:
          PlayerStatusType = other.PlayerStatusType;
          break;
        case UpdateTypeOneofCase.PlayerTransformType:
          PlayerTransformType = other.PlayerTransformType;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            updateType_ = input.ReadEnum();
            updateTypeCase_ = UpdateTypeOneofCase.PlayerStatusType;
            break;
          }
          case 16: {
            updateType_ = input.ReadEnum();
            updateTypeCase_ = UpdateTypeOneofCase.PlayerTransformType;
            break;
          }
        }
      }
    }

  }

  public sealed partial class WolrdUpdateType : pb::IMessage<WolrdUpdateType> {
    private static readonly pb::MessageParser<WolrdUpdateType> _parser = new pb::MessageParser<WolrdUpdateType>(() => new WolrdUpdateType());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WolrdUpdateType> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DnD.Service.ClientRequestReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WolrdUpdateType() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WolrdUpdateType(WolrdUpdateType other) : this() {
      switch (other.UpdateTypeCase) {
        case UpdateTypeOneofCase.PropsUpdateType:
          PropsUpdateType = other.PropsUpdateType;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WolrdUpdateType Clone() {
      return new WolrdUpdateType(this);
    }

    /// <summary>Field number for the "propsUpdateType" field.</summary>
    public const int PropsUpdateTypeFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DnD.Service.PropsUpdateType PropsUpdateType {
      get { return updateTypeCase_ == UpdateTypeOneofCase.PropsUpdateType ? (global::DnD.Service.PropsUpdateType) updateType_ : global::DnD.Service.PropsUpdateType.DeleteProp; }
      set {
        updateType_ = value;
        updateTypeCase_ = UpdateTypeOneofCase.PropsUpdateType;
      }
    }

    private object updateType_;
    /// <summary>Enum of possible cases for the "updateType" oneof.</summary>
    public enum UpdateTypeOneofCase {
      None = 0,
      PropsUpdateType = 1,
    }
    private UpdateTypeOneofCase updateTypeCase_ = UpdateTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateTypeOneofCase UpdateTypeCase {
      get { return updateTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUpdateType() {
      updateTypeCase_ = UpdateTypeOneofCase.None;
      updateType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WolrdUpdateType);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WolrdUpdateType other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PropsUpdateType != other.PropsUpdateType) return false;
      if (UpdateTypeCase != other.UpdateTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (updateTypeCase_ == UpdateTypeOneofCase.PropsUpdateType) hash ^= PropsUpdateType.GetHashCode();
      hash ^= (int) updateTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (updateTypeCase_ == UpdateTypeOneofCase.PropsUpdateType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PropsUpdateType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (updateTypeCase_ == UpdateTypeOneofCase.PropsUpdateType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PropsUpdateType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WolrdUpdateType other) {
      if (other == null) {
        return;
      }
      switch (other.UpdateTypeCase) {
        case UpdateTypeOneofCase.PropsUpdateType:
          PropsUpdateType = other.PropsUpdateType;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            updateType_ = input.ReadEnum();
            updateTypeCase_ = UpdateTypeOneofCase.PropsUpdateType;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
